### ISSUE TITLE
Too verbose output

### ISSUE THREAD

**Issue by mizdebsk** [keszybz/add-determinism#17]
Output of add-determinism is very verbose, polluting build log files and making them harder to read.

For example, in [build.log](https://kojipkgs.fedoraproject.org//packages/xalan-j2/2.7.3/4.fc41/data/logs/noarch/build.log) of build [xalan-j2-2.7.3-4.fc41](https://koji.fedoraproject.org/koji/buildinfo?buildID=2463224) lines produced by add-determinism make up over 96 % of the content of the log file.

**Comment by mizdebsk** [comment]
Thanks, it's better now, but this issue is still not fully fixed.
I still see numerous "replacing with normalized version" info messages, for example in
https://kojipkgs.fedoraproject.org//packages/apache-commons-net/3.11.0/3.fc41/data/logs/noarch/build.log

**Comment by mizdebsk** [comment]
On second though I suppose this is not a big deal.
For javadoc we are going to start using "-notimestamp" option anyway, which should prevent timestaps from being included in the first place.
Number of other non-javadoc files should low-enough so that these log entries won't be that problematic.

**Comment by keszybz** [comment]
>  I still see numerous "replacing with normalized version" info messages, for example in

Yeah, that is intentional. I *can* drop those, but I thought it's better to err on the side of verbosity, esp. in the beginning. I don't want people to be surprised when the content changes. Dunno, maybe limit this it ~20 lines or so?
