### ISSUE TITLE
Option to fail the build when non-determinism is found

### ISSUE THREAD

**Issue by mizdebsk** [keszybz/add-determinism#19]
Please add an option to fail the build when non-determinism is found.

Instead of replacing non-deterministic files with "normalized" versions, I would prefer to rely on upstream build features to avoid non-determinism in the first place, whenever possible. Then I could disable add-determinism BRP for packages with builds that are known to be deterministic.

But even with deterministic builds, it would be still useful to run add-determinism BRP to make sure the build is indeed deterministic and avoid regressions (reintroducing non-determinism in future updates). Therefore in case add-determinism finds any non-determinism then I would like it to fail the build and let package maintainer fix the underlying build issue, instead of trying to "fix" non-determinism by "normalizing" files.

The whole input should be processed before failing, so that the user sees all cases of non-determinism in the build, not just the first one.

**Comment by keszybz** [comment]
PTAL at #20. Maybe you have some comments about the interface or output.
