### ISSUE TITLE
Strip timestamps from plain ZIPs?

### ISSUE THREAD

**Issue by swsnr** [keszybz/add-determinism#46]
I have a plain ZIP file I'd like to strip timestamps from.  I figured that since JARs are just glorified ZIPs I should be able to use the JAR handler for this purpose, but I can't seem to get it work:

```console
$ add-determinism --version
add-determinism 0.4.2
$ touch foo
$ command ls -l foo
[...] 0 15. Nov 09:54 foo
$ 7z a foo.zip foo
[...]
Everything is Ok
$ file foo.zip 
foo.zip: Zip archive data, at least v1.0 to extract, compression method=store
$ unzip -l foo.zip 
Archive:  foo.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-11-15 09:54   foo
---------                     -------
        0                     1 file
$ add-determinism --ignore-extension --handler jar foo.zip 
Scanned 0 directories and 1 files,
               processed 1 inodes,
               0 modified (0 replaced + 0 rewritten),
               0 unsupported format, 0 errors
$ unzip -l foo.zip
Archive:  foo.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-11-15 09:54   foo
---------                     -------
        0                     1 file
```

Even though I tried to force the jar handler the file still carries a timestamp along the zip entry :thinking: 

Am I using `add-determinism` wrong?

**Comment by keszybz** [comment]
I "extended" (actually mostly renamed ;)) the .jar handler to support .zip files.

Your example wasn't working because SOURCE_DATE_EPOCH wasn't set. I added another commit to fail verbosely in that case. PTAL.

https://github.com/keszybz/add-determinism/pull/47

**Comment by swsnr** [comment]
Exporting `SOURCE_DATE_EPOCH` prior to the command works, even in the current version, thanks a lot for this tip :pray: 

The changes look even better; in particular rewriting timestamps of entries regardless of whether they are newer or older makes it possible to consistently timestamp the whole ZIP by the latest commit.

Many thanks :pray:
